#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : kwindowsystem
Version  : 5.90.0
Release  : 302
URL      : https://download.kde.org/stable/frameworks/5.90/kwindowsystem-5.90.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.90/kwindowsystem-5.90.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kwindowsystem-data = %{version}-%{release}
Requires: kwindowsystem-lib = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libxcb-dev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(xcb)
BuildRequires : qtbase-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# KWindowSystem
Access to the windowing system
## Introduction
Convenience access to certain properties and features of the windowing system.

%package data
Summary: data components for the kwindowsystem package.
Group: Data

%description data
data components for the kwindowsystem package.


%package dev
Summary: dev components for the kwindowsystem package.
Group: Development
Requires: kwindowsystem-lib = %{version}-%{release}
Requires: kwindowsystem-data = %{version}-%{release}
Provides: kwindowsystem-devel = %{version}-%{release}
Requires: kwindowsystem = %{version}-%{release}

%description dev
dev components for the kwindowsystem package.


%package lib
Summary: lib components for the kwindowsystem package.
Group: Libraries
Requires: kwindowsystem-data = %{version}-%{release}

%description lib
lib components for the kwindowsystem package.


%prep
%setup -q -n kwindowsystem-5.90.0
cd %{_builddir}/kwindowsystem-5.90.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643433654
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
%cmake .. -DKDE_INSTALL_CONFDIR=/usr/share/xdg \
-DBUILD_TESTING:BOOL=OFF
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1643433654
rm -rf %{buildroot}
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/af/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ar/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/as/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ast/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/az/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/be/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/be@latin/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/bg/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/bn/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/bn_IN/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/br/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/bs/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ca/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/crh/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/cs/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/csb/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/cy/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/da/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/de/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/el/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/eo/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/es/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/et/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/eu/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/fa/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/fi/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/fr/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/fy/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ga/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/gd/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/gl/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/gu/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ha/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/he/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hi/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hne/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hr/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hsb/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hu/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/hy/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ia/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/id/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/is/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/it/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ja/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ka/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/kk/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/km/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/kn/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ko/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ku/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/lb/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/lt/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/lv/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/mai/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/mk/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ml/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/mr/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ms/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/nb/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/nds/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ne/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/nl/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/nn/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/oc/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/or/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/pa/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/pl/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ps/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/pt/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ro/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ru/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/se/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/si/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sk/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sl/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sq/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sr/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/sv/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ta/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/te/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/tg/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/th/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/tr/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/tt/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/ug/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/uk/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/uz/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/vi/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/wa/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/xh/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/zh_HK/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/kwindowsystem5_qt.qm
/usr/share/qlogging-categories5/kwindowsystem.categories
/usr/share/qlogging-categories5/kwindowsystem.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KWindowSystem/KKeyServer
/usr/include/KF5/KWindowSystem/KSelectionOwner
/usr/include/KF5/KWindowSystem/KSelectionWatcher
/usr/include/KF5/KWindowSystem/KStartupInfo
/usr/include/KF5/KWindowSystem/KUserTimestamp
/usr/include/KF5/KWindowSystem/KWindowEffects
/usr/include/KF5/KWindowSystem/KWindowInfo
/usr/include/KF5/KWindowSystem/KWindowShadow
/usr/include/KF5/KWindowSystem/KWindowShadowTile
/usr/include/KF5/KWindowSystem/KWindowSystem
/usr/include/KF5/KWindowSystem/KXMessages
/usr/include/KF5/KWindowSystem/NETWM
/usr/include/KF5/KWindowSystem/config-kwindowsystem.h
/usr/include/KF5/KWindowSystem/fixx11h.h
/usr/include/KF5/KWindowSystem/kkeyserver.h
/usr/include/KF5/KWindowSystem/kkeyserver_x11.h
/usr/include/KF5/KWindowSystem/kmanagerselection.h
/usr/include/KF5/KWindowSystem/kselectionowner.h
/usr/include/KF5/KWindowSystem/kselectionwatcher.h
/usr/include/KF5/KWindowSystem/kstartupinfo.h
/usr/include/KF5/KWindowSystem/kusertimestamp.h
/usr/include/KF5/KWindowSystem/kwindoweffects.h
/usr/include/KF5/KWindowSystem/kwindowinfo.h
/usr/include/KF5/KWindowSystem/kwindowshadow.h
/usr/include/KF5/KWindowSystem/kwindowsystem.h
/usr/include/KF5/KWindowSystem/kwindowsystem_export.h
/usr/include/KF5/KWindowSystem/kxmessages.h
/usr/include/KF5/KWindowSystem/netwm.h
/usr/include/KF5/KWindowSystem/netwm_def.h
/usr/include/KF5/KWindowSystem/private/kwindoweffects_p.h
/usr/include/KF5/KWindowSystem/private/kwindowinfo_p.h
/usr/include/KF5/KWindowSystem/private/kwindowshadow_p.h
/usr/include/KF5/KWindowSystem/private/kwindowsystem_p.h
/usr/include/KF5/KWindowSystem/private/kwindowsystemplugininterface_p.h
/usr/include/KF5/kwindowsystem_version.h
/usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake
/usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfigVersion.cmake
/usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemTargets-none.cmake
/usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemTargets.cmake
/usr/lib64/libKF5WindowSystem.so
/usr/lib64/qt5/mkspecs/modules/qt_KWindowSystem.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5WindowSystem.so.5
/usr/lib64/libKF5WindowSystem.so.5.90.0
/usr/lib64/qt5/plugins/kf5/kwindowsystem/KF5WindowSystemWaylandPlugin.so
/usr/lib64/qt5/plugins/kf5/kwindowsystem/KF5WindowSystemX11Plugin.so
